### ISSUE TITLE
operator PR passed, but not updated in the indexes.

### ISSUE THREAD

**Issue by DanArlowski** [redhat-openshift-ecosystem/community-operators-prod#1393]
We create a PR For sosivio operator, which passed the ci https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1392 \
it was merged to main, passed on main, too, but never updated in the operatorhub in OCP (it happened in operatorhub, too)

info:
- we use semver mode (in `ci.yml`)
- we updated from 1.4.1 to 1.4.1-1
- link to [operatorhub](https://operatorhub.io/operator/sosivio)

(no link to openshift for obvious reasons :) )

**Comment by mvalarh** [comment]
We are looking it to this and reporting bug at https://github.com/operator-framework/operator-registry/issues/993

**Comment by mvalarh** [comment]
According to https://github.com/operator-framework/operator-registry/issues/993#issuecomment-1184474719 i would recommend you to have versions like this https://github.com/redhat-openshift-ecosystem/community-operators-pipeline/tree/main/operators/sosivio . Since you use `semver` mode in `operatorhub.io` you would see only latest version in stable channel.
