### ISSUE TITLE
ARM64 support for the KEDA operator

### ISSUE THREAD

**Issue by odidev** [redhat-openshift-ecosystem/community-operators-prod#2879]
Hi @dmesser , 

I have been trying to [install](https://keda.sh/docs/2.10/deploy/) `KEDA` from the `OperatorHub` on the **Arm64** platform.   

After deploying an OpenShift cluster on Arm64 when I search for KEDA operator in the operator hub, it shows `"no results found"`.

![Screenshot (554)](https://github.com/redhat-openshift-ecosystem/community-operators-prod/assets/40816837/31e1720f-bbc9-4e83-909b-514f1d620060)

Do you have any plans to release it for Arm64?

**Comment by mporrato** [comment]
@odidev what openshift version are you testing with?

**Comment by odidev** [comment]
Hi @mporrato , 

> [@odidev](https://github.com/odidev) what openshift version are you testing with? 

I’m using openshift version **`4.13`**. I have used this [document](https://docs.openshift.com/container-platform/4.13/installing/installing_aws/installing-aws-default.html) to deploy the cluster. 

**ENVIROMENT:-** 
```console
$ cat /etc/os-release  
 
PRETTY_NAME="Ubuntu 22.04 LTS"   
NAME="Ubuntu"   
VERSION_ID="22.04"   
VERSION="22.04 LTS (Jammy Jellyfish)"   
VERSION_CODENAME=jammy   
ID=ubuntu   
ID_LIKE=debian   
HOME_URL="https://www.ubuntu.com/"  
SUPPORT_URL="https://help.ubuntu.com/"  
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"  
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"  
UBUNTU_CODENAME=jammy
```

**Comment by dmesser** [comment]
It seems KEDA is deprecated here. It moved into the Custom Metrics Autoscaler project that is now officially part of OpenShift's catalog of supported operators. I am not sure if that supports arm64, if it doesn't that would be an official request for enhancement.

While KEDA might still be present in the community catalog it doesn't seem to support arm64 because the [label metadata](https://docs.openshift.com/container-platform/4.13/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-multi-arch_osdk-generating-csvs) is missing that would indicate that. That's you don't see it in your arm64 cluster. You should use the custom metric autoscaler.
