### ISSUE TITLE
Prometheus Operator outdated version

### ISSUE THREAD

**Issue by gburges** [redhat-openshift-ecosystem/community-operators-prod#3267]
Hello!

We received a request from our tenants to upgrade the prometheus operator in our environments, and the community operator hasn't been updated for a while (the latest version now is 0.68.0). Is there a reason for it, and/or is there a suggestion workaround, or someone just needs a pr?

**Comment by mporrato** [comment]
@gburges operators hosted in this repo are community-contributed.
The prometheus operator does not have any registered maintainer but I can see that it used to be kept up to date by @ctrought . 
As always, contributions are welcome :)

**Comment by ctrought** [comment]
Originally I had planned to keep this updated, since we had the same problem and had tenants using it to and there were newer features we were missing out on available in newer versions of prometheus operator however soon after came to realization this might not be possible 😭 

1. OpenShift has cluster operators (COs), one being the cluster monitoring operator which is managed by the cluster version operator (CVO) and not by OLM. This cluster monitoring operator from Red Hat (prometheus) uses the same API group "monitoring.coreos.com" as the community prometheus operator so there is a conflict between the CRDs wanted by each operator, OLM wants to install version A (newer) for the prometheus operator while CVO wants to install version B (older) for the cluster monitoring operator. CVO reconciles constantly, so after OLM installs Prometheus community operator which contains newer CRDs the CVO will reconcile and replace the CRDs with the versions provided by the cluster monitoring operator. The community prometheus operator would then be running with mismatched CRDs which might functionally work,  but some features (changed fields in the CRDs) would not available to use, and there is always the potential of the community prometheus operator breaking depending on the drift between the prometheus operator (community) and the Red Hat cluster monitoring operator.

2. If enabling User Workload Monitoring on OCP, the community prometheus cannot be installed. I figure most OCP users would probably want to leverage UWM, so in combination with above opted to abandon the idea of updating the operator.
